# Generated by Django 4.2.3 on 2025-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
